# Use the Bitnami Spark base image
FROM bitnami/spark:3.3.3

USER root
WORKDIR /usr/src/app

ENV POSTGRES_JDBC_VERSION 42.4.1

RUN apt-get update && apt-get install -y curl 

# Download the PostgreSQL JDBC driver
RUN curl -o /opt/bitnami/spark/jars/postgresql-jdbc.jar \
    https://jdbc.postgresql.org/download/postgresql-${POSTGRES_JDBC_VERSION}.jar

# COPY requirements.txt .
# RUN pip3 install --no-cache-dir -r requirements.txt
# COPY src/ .

# Set the entrypoint to run spark-submit
ENTRYPOINT ["/opt/bitnami/spark/bin/spark-submit", "--master", "spark://spark-master:7077", \
            "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.3", \
            "--jars", "/opt/bitnami/spark/jars/postgresql-jdbc.jar", \
            # "--conf", "spark.kafka.bootstrap.servers=broker:29092", \
            "spark_app.py"]
