name: scraping
channels:
  - defaults
dependencies:
  - python
  - pip
  - jupyter
  - pip:
      - confluent-kafka==2.3.0
      - python-dotenv==1.0.0
      - webdriver-manager==4.0.1
      - selenium==4.15.0
