version: "3"

services:
  postgres:
    image: "postgres:15.4-bookworm"
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: crypto_viz
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default
      - kafka-network

  pgadmin:
    image: "dpage/pgadmin4"
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8092:80"
    volumes:
      - pg-admin-data:/var/lib/pgadmin
    networks:
      - default
      - kafka-network

networks:
  default:
    name: db-network
  kafka-network:
    external: true

volumes:
  db-data:
  pg-admin-data:
