version: "3"
services:
  scraper:
    build: .
    image: scraper:latest
    env_file:
      - ./.env
    volumes:
      - scraper-data:/usr/src/app

networks:
  default:
    name: kafka-network
    external: true
      
      

volumes:
  scraper-data:
