{
 "title": "Cryptocurrency Infos",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "selectedTimestamp",
    "query": "SELECT DISTINCT to_char(timestamp , 'YYYY-MM-DD\" \"HH24:MI') FROM crypto_test ORDER BY to_char(timestamp , 'YYYY-MM-DD\" \"HH24:MI') DESC"
   },
   {
    "name": "selectedNames",
    "label": "Cryptocurrency",
    "query": "SELECT DISTINCT name \nFROM crypto_test"
   },
   { "name": "selectedOrder", "label": "selectedOrder", "query": "ASC, DESC" }
  ]
 },
 "panels": [
  {
   "title": "Cryptocurrency % change",
   "type": "barchart",
   "description": "Percentage change in the last 24 hours. When sorted by % Chg, we only include assets with at least 1 BTC top tier volume in the last 24 hours.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "rawSql": "SELECT name || ' (' || symbol || ')' as name_with_symbol, percentage_change\r\nFROM crypto_test \r\nWHERE timestamp = '${selectedTimestamp}'::Timestamp \r\nAND name IN (${selectedNames:sqlstring})\r\nORDER BY price ${selectedOrder};"
    }
   ]
  },
  {
   "title": "Cryptocurrency market cap",
   "type": "barchart",
   "description": "Market Cap = Total Supply * Price. Where Total Supply includes coins held by the project team, locked in smart contracts or escrow. Supply that is verifiably burned is not included. A penalty is applied to coins with low liquidity.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT name || ' (' || symbol || ')' as name_with_symbol, market_cap\r\nFROM crypto_test \r\nWHERE timestamp = '${selectedTimestamp}'::Timestamp \r\nAND name IN (${selectedNames:sqlstring})\r\nORDER BY price ${selectedOrder};"
    }
   ]
  },
  {
   "title": "Cryptocurrency prices",
   "type": "barchart",
   "description": "The last trade price. When sorted by price, we only include assets with at least 1 BTC top tier volume in the last 24 hours.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT name || ' (' || symbol || ')' as name_with_symbol, price\r\nFROM crypto_test \r\nWHERE timestamp = '${selectedTimestamp}'::Timestamp \r\nAND name IN (${selectedNames:sqlstring})\r\nORDER BY price ${selectedOrder};"
    }
   ]
  },
  {
   "title": "Cryptocurrency volumes",
   "type": "barchart",
   "description": "Volume in the last 24 hours across all exchanges.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT name || ' (' || symbol || ')' as name_with_symbol, volume\r\nFROM crypto_test \r\nWHERE timestamp = '${selectedTimestamp}'::timestamp\r\nAND name IN (${selectedNames:sqlstring})\r\nORDER BY volume ${selectedOrder};"
    }
   ]
  }
 ]
}