{
 "title": "Historical cryptocurrency dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cryptoname",
    "query": "SELECT DISTINCT name FROM crypto_test "
   }
  ]
 },
 "panels": [
  {
   "title": "Price Crypto en (USD)",
   "type": "timeseries",
   "description": "The last trade price. When sorted by price, we only include assets with at least 1 BTC top tier volume in the last 24 hours.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT name, price, timestamp as time\r\nFROM crypto_test\r\nWHERE name in (${cryptoname:sqlstring})"
    }
   ]
  },
  {
   "title": "Crypto Market Cap (USD)",
   "type": "timeseries",
   "description": "Market Cap = Total Supply * Price. Where Total Supply includes coins held by the project team, locked in smart contracts or escrow. Supply that is verifiably burned is not included. A penalty is applied to coins with low liquidity.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT name, market_cap, timestamp as time\r\nFROM crypto_test\r\nWHERE name in (${cryptoname:sqlstring})"
    }
   ]
  },
  {
   "title": "Volume Crypto in (USD)",
   "type": "timeseries",
   "description": "Volume in the last 24 hours across all exchanges.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT name, volume, timestamp as time\r\nFROM crypto_test\r\nWHERE name in (${cryptoname:sqlstring})"
    }
   ]
  },
  {
   "title": "Percentage change crypto",
   "type": "timeseries",
   "description": "Percentage change in the last 24 hours. When sorted by % Chg, we only include assets with at least 1 BTC top tier volume in the last 24 hours.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "rawSql": "SELECT name, percentage_change, timestamp as time\r\nFROM crypto_test\r\nWHERE name in (${cryptoname:sqlstring})"
    }
   ]
  }
 ]
}