version: "3.8"
services:
  crypto_react:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
    working_dir: /app
    command: /bin/sh -c "npm install && npm run dev"
    networks:
      - api-network

networks:
  api-network:
    external: true