# Stage 1 : build
FROM node:latest as build

WORKDIR /app

COPY ./app .

RUN npm install

RUN npm run build


# Stage 2 : deployment
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
