FROM node:latest

WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

EXPOSE 8080

# Start the application
# CMD [ "npm", "run", "dev" ]
CMD [ "tail", "-f", "//dev//null" ]
