version: "3.8"
services:
  crypto_api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=processed_data_db
    networks:
      - db-network
      - api-network
    working_dir: /app
    command: /bin/sh -c "npm install && npm run dev"
    # command: tail -f /dev/null

networks:
  db-network:
    external: true
  api-network:
    external: true



